config/routes.rb
Chalk::Application.routes.draw do
  resources :tests

  resources :subjects

  resources :teachers

  resources :standards

  get "master/index"
  resources :marks

  resources :students
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/academics',   to: 'static_pages#academics',   via: 'get'
  match '/timetable',    to: 'static_pages#timetable',    via: 'get'
  match '/analytics',   to: 'static_pages#analytics',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/calendar(/:year(/:month))' => 'static_pages#calendar', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/models/event.rb
class Event < ActiveRecord::Base
has_event_calendar
end

app/models/mark.rb
class Mark < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/standard.rb
class Standard < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   @user = current_user
  end

  def help
  end

  def about
  end
  
  def academics
  end
 
  def analytics
  end

  def timetable
  end

  def calendar
   @month = (params[:month] || Time.zone.now.month).to_i
   @year = (params[:year] || Time.zone.now.year).to_i
   @shown_month = Date.civil(@year, @month)
   @event_strips = Event.event_strips_for_month(@shown_month)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
   end
      
   def signed_in?
    !current_user.nil?
   end

   def current_user=(user)
    @current_user = user
   end

   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
   end

   def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
   end
 
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

 def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end

  def event_calendar_options
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"
    }
  end

  def event_calendar
    calendar event_calendar_options do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_courses.html.erb
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
  $(function () {
    $('.nav.nav-tabs.nav-append-content ').tabs()
  })
</script>
<div class="panel panel-primary" style="position:absolute;left:400px;top:50px;border-color:#dddddd">
       <ul class="nav nav-tabs nav-append-content">
            <li class="active"><a href="#tab1" data-target="#tab1" data-toggle="tab">Current</a></li>
            <li><a href="#tab2" data-target="#tab2" data-toggle="tab">Homeworks</a></li>
            <li><a href="#tab3" data-target="#tab3" data-toggle="tab">Study Material</a></li>
            <li><a href="#tab4" data-target="#tab4" data-toggle="tab">Question Papers</a></li>
          </ul> <!-- /tabs -->

          <div class="tab-content">
            <div class="tab-pane active" id="tab1">
              <li>Newtons Laws done in todays class,be prepared for Law of Conservation of Momemtum tomorrow &nbsp;&nbsp; 10th October</li>
              <li>Solved Problems from Kinematics in todays class,new chapter Dynamics will start tomorrow &nbsp;&nbsp; 9th October</li>
              <li>Differential analysis of distance,velocity and acceleration completed,lets solve problems tomorrow &nbsp;&nbsp; 8th October</li>
              <li>Constant Speed and Acceleration covered today,tomorrow lets discuss on change of velocity and acceleration with time &nbsp;&nbsp; 10th October</li>
            </div>
   
            <!-- /tabs -->
            <div class="tab-pane" id="tab2">
              <li>Solve problems 1-5 from Chapter 5 Dynamics &nbsp;&nbsp; 10th October</li>
              <li>Solve all unsolved problems from Chapter 4 Kinematics &nbsp;&nbsp; 9th October</li>
              <li>Read about time varying velocity and acceleration from Chapter 4 Kinematics &nbsp;&nbsp; 9th October</li>
            </div>

            <!-- /tabs -->
            <div class="tab-pane" id="tab3">
              <p><a href="#">Click here to view the study material for Newtons Law of Motion</a></p>
               <p><a href="#">Click here to view the study material for Time varying velocity and acceleration</a></p>
               <p><a href="#">Click here to view the study material for Constant velocity and acceleration</a></p>
            </div>

           <div class="tab-pane" id="tab4">
              <p><a href="#">Click here to view the last year's question paper for Unit Test 1</a></p>
            </div>
          </div> <!-- /tab-content -->

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
 <div class="container">
   <div id="about-wraper">
 <!--
 <h1 style="position:absolute;top:83px;left:520px;color:#fff">About Us</h1>
 -->
 <legend><strong style="color:#34495e;">About Us</strong></legend>
 <p>We are just a bunch of three kids trying to <strong>revolutionize the way</strong> schools interact with students.ChalkSpace is the online personal space for students where they can see all the stuff related to their school let it be homeworks,upcoming exams or notices,study material,past question papers etc.Chalkspace also acts a management tool for Schools to manage all the things that involve running a school and also provides a great interface for teachers to keep track of everything along with the cool analytics of grades,attendence etc of each and every student.</p>
</div>
</div>
</body>
</htmk>

app/views/static_pages/academics.html.erb
<% provide(:title, 'Academics') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
     <title>ChalkSpace | <%= yield(:title) %></title>
    <script>
     $(function() {
      $( "#tabs" ).tabs();
       });
  </script>
  </head>
  <body>
    
      <% if signed_in? %>
      <div class="row demo-samples" style="position:relative;left:-150px;bottom:0;">
        <div class="col-md-4">
           <div class="row demo-navigation" style="position:relative;left:10px;bottom:0;">
            <div class="col-md-6" >
              <div class="btn-toolbar" style="position:relative;left:23px;bottom:0;">
                <div class="btn-group">
                  <%= link_to image_tag("icons/Mortarboard@2x.png", alt: "Rails", width:"30px",height:"22px"),academics_path,class:"btn btn-primary active",name:"academics",value:"courses" %>
                  <%= link_to image_tag("icons/Watches@2x.png", alt: "Rails", width:"22px",height:"22px"),timetable_path,class:"btn btn-primary",name:"academics",value:"timetable" %>
                  <%= link_to image_tag("icons/Calendar@2x.png", alt: "Rails", width:"22px",height:"22px"),"/calendar",class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Clipboard@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Mail@2x.png", alt: "Rails", width:"21px",height:"22px"),root_path,class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Graph@2x.png", alt: "Rails", width:"22px",height:"22px"),analytics_path,class:"btn btn-primary" %>
                </div>
              </div>
          <div class="demo-col pull-left" style="position:relative;top:-10px;left:5px">
          <ul class="nav nav-list nav-list-vivid">
            <li class="nav-header">Courses</li>
            <li>
              <a href="#fakelink">
                Mathematics
              </a>
            </li>
            <li class="active">
              <a href="#fakelink">
                Physical Sciences
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Biological Sciences
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#fakelink">
                Hindi
              </a>
            </li>
            <li>
              <a href="#fakelink">
                English
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Programming
              </a>
            </li>
          </ul>
        </div> <!-- /nav-list -->
      <%= render 'static_pages/courses' %>
      <% else %>
      <div class="center hero-unit">
      <h1>Welcome to the ChalkSpace</h1>

      <h2>
      This is the home page for the
       <a href="http://railstutorial.org/">ChalkSpace</a>
        sample application.<br>
     </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
     </div>
     <% end %>
   
  </body>
</html>

app/views/static_pages/analytics.html.erb
<% provide(:title, 'Analytics') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
     <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
    
      <% if signed_in? %>
      <div class="row demo-samples" style="position:relative;left:-150px;bottom:0;">
        <div class="col-md-4">
           <div class="row demo-navigation" style="position:relative;left:10px;bottom:0;">
            <div class="col-md-6" >
              <div class="btn-toolbar" style="position:relative;left:23px;bottom:0;">
                <div class="btn-group">
                  <%= link_to image_tag("icons/Mortarboard@2x.png", alt: "Rails", width:"30px",height:"22px"),academics_path,class:"btn btn-primary",name:"academics",value:"courses" %>
                  <%= link_to image_tag("icons/Watches@2x.png", alt: "Rails", width:"22px",height:"22px"),timetable_path,class:"btn btn-primary",name:"academics",value:"timetable" %>
                  <%= link_to image_tag("icons/Calendar@2x.png", alt: "Rails", width:"22px",height:"22px"),"/calendar",class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Clipboard@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Mail@2x.png", alt: "Rails", width:"21px",height:"22px"),root_path,class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Graph@2x.png", alt: "Rails", width:"22px",height:"22px"),analytics_path,class:"btn btn-primary active" %>
                </div>
              </div>
          <div class="demo-col pull-left" style="position:relative;top:-10px;left:5px">
          <ul class="nav nav-list nav-list-vivid">
            <li class="nav-header">Analytics</li>
            <li>
              <a href="#fakelink">
                Overall
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Mathematics
              </a>
            </li>
            <li class="active">
              <a href="#fakelink">
                Physical Sciences
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Biological Sciences
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#fakelink">
                Hindi
              </a>
            </li>
            <li>
              <a href="#fakelink">
                English
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Programming
              </a>
            </li>
          </ul>
        </div> <!-- /nav-list -->
      <h2 align="center">Coming Soon</h2>
      <% else %>
      <div class="center hero-unit">
      <h1>Welcome to the ChalkSpace</h1>

      <h2>
      This is the home page for the
       <a href="http://railstutorial.org/">ChalkSpace</a>
        sample application.<br>
     </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
     </div>
     <% end %>
   
  </body>
</html>

app/views/static_pages/calendar.html.erb
<%= stylesheet_link_tag "event_calendar" %>
<%= javascript_include_tag "event_calendar" %>
<% provide(:title, 'Calendar') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
     <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
    
      <% if signed_in? %>
      <div class="row demo-samples" style="position:relative;left:-150px;bottom:0;">
        <div class="col-md-4">
           <div class="row demo-navigation" style="position:relative;left:10px;bottom:0;">
            <div class="col-md-6" >
              <div class="btn-toolbar" style="position:relative;left:23px;bottom:0;">
                <div class="btn-group">
                  <%= link_to image_tag("icons/Mortarboard@2x.png", alt: "Rails", width:"30px",height:"22px"),academics_path,class:"btn btn-primary",name:"academics",value:"courses" %>
                  <%= link_to image_tag("icons/Watches@2x.png", alt: "Rails", width:"22px",height:"22px"),timetable_path,class:"btn btn-primary",name:"academics",value:"timetable" %>
                  <%= link_to image_tag("icons/Calendar@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary active" %>
                  <%= link_to image_tag("icons/Clipboard@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Mail@2x.png", alt: "Rails", width:"21px",height:"22px"),root_path,class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Graph@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                </div>
              </div>
          <div class="demo-col pull-left" style="position:relative;top:-10px;left:5px">
          <ul class="nav nav-list nav-list-vivid">
            <li class="nav-header">Calendar</li>
            <li>
              <a href="#fakelink">
                View Holidays
              </a>
            </li>
            <li class="active">
              <a href="#fakelink">
                Add Events
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Settings
              </a>
            </li>
          </ul>
        </div> <!-- /nav-list -->
      <div style="position:absolute;width:600px;height:450px;left:390px;top:10px;">
            <%= raw(event_calendar) %>
      </div>
      <% else %>
      <div class="center hero-unit">
      <h1>Welcome to the ChalkSpace</h1>

      <h2>
      This is the home page for the
       <a href="http://railstutorial.org/">ChalkSpace</a>
        sample application.<br>
     </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
     </div>
     <% end %>
   
  </body>
</html>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
    
      <% if signed_in? %>
      <div class="row demo-samples" style="position:relative;left:-150px;bottom:0;">
        <div class="col-md-4">
           <div class="row demo-navigation" style="position:relative;left:10px;bottom:0;">
            <div class="col-md-6" >
              <div class="btn-toolbar" style="position:relative;left:23px;bottom:0;">
                <div class="btn-group">
                  <%= link_to academics_path,class:"btn btn-primary",name:"academics" do %><%= image_tag("icons/Mortarboard@2x.png", alt: "Rails", width:"30px",height:"22px",:data => {:toggle=>"tooltip",:tooltip=>{style:"inner"}},title:"Checkout your courses here") %><% end %>
                  <%= link_to image_tag("icons/Watches@2x.png", alt: "Rails", width:"22px",height:"22px",:data => {:toggle=>"tooltip",:tooltip=>{style:"inner"}},title:"Checkout your timetable here"),timetable_path,class:"btn btn-primary",name:"academics",value:"timetable" %>
                  <%= link_to image_tag("icons/Calendar@2x.png", alt: "Rails", width:"22px",height:"22px",:data => {:toggle=>"tooltip",:tooltip=>{style:"inner"}},title:"Checkout your schedule here"),"/calendar",class:"btn btn-primary",title:"Calender" %>
                  <%= link_to image_tag("icons/Clipboard@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Mail@2x.png", alt: "Rails", width:"21px",height:"22px",:data => {:toggle=>"tooltip",:tooltip=>{style:"inner"}},title:"Checkout your notices here"),root_path,class:"btn btn-primary active" %>
                  <%= link_to image_tag("icons/Graph@2x.png", alt: "Rails", width:"22px",height:"22px",:data => {:toggle=>"tooltip",:tooltip=>{style:"inner"}},title:"Checkout your Grades here"),analytics_path,class:"btn btn-primary" %>
                </div>
              </div>
          <div class="demo-col pull-left" style="position:relative;top:-10px;left:5px">
          <ul class="nav nav-list nav-list-vivid">
            <li class="nav-header">Notices</li>
            <li>
              <a href="#fakelink">
                Recent
              </a>
            </li>
            <li class="active">
              <a href="#fakelink">
                All
              </a>
            </li>
            <li>
              <a href="#fakelink">
                General
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#fakelink">
                Academic
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Extra-Curricular
              </a>
            </li>
            <li class="nav-header">Messages</li>
            <li>
              <a href="#fakelink">
                Inbox
               <span class="nav-counter">19</span>
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Outbox
              </a>
            </li>
         
          </ul>
        </div> <!-- /nav-list -->
      <div class="panel panel-primary" style="position:absolute;left:400px;top:50px;border-color:#dddddd">
         <div class="panel-heading"><span class="fui-list"></span>  Recent Notices</div>
            <ul class="list-group">
               <li class="list-group-item">Half Yearly Exams time table has been uploaded,please check your exams section</li>
               <li class="list-group-item">2nd October is a holiday on account of Gandhi Jayanthi</li>
               <li class="list-group-item">Our School won the best School Award for this year,cheers to all</li>
               <li class="list-group-item">We congratulate the cricket team of our team for winning the inter school tournament</li>
               <li class="list-group-item">Dassera Holidays from 10th October to 18th October</li>
            <div class="pagination" style="position:relative;left:120px;">
              <ul>
                <li class="previous"><a href="#fakelink" class="fui-arrow-left"></a></li>
                <li class="active"><a href="#fakelink">1</a></li>
                <li><a href="#fakelink">2</a></li>
                <li><a href="#fakelink">3</a></li>
                <li><a href="#fakelink">4</a></li>
                <li class="next"><a href="#fakelink" class="fui-arrow-right"></a></li>
              </ul>
            </div> <!-- /pagination -->
            </ul>
       </div> 
      <% else %>
      <div id="wrapper">
      <p align="center" style="color:#34495e"><strong style="font-size:30px;">Welcome to ChalkSpace</strong><br><strong>We are revolutionazing the way schools interact with students.Signup to see the demo of our beta product</strong></p>

     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success",style:"position:absolute;left:450px;top:20px" %>
     </div>
     <% end %>
<!--
      <div class="container">

        <div id="login-wraper">
            <form class="form login-form">
                <legend>Sign in to <span class="blue">ChalkSpace</span></legend>
            
                <div class="body">
                    <label>Username</label>
                    <input type="text" style="width:250px;">
                    
                    <label>Password</label>
                    <input type="password" style="width:250px;height:20000px;">
                </div>
            
                <div class="footer">
                    <button type="submit" class="btn btn-success">Login</button>
                </div>
            
            </form>
        </div>

    </div>
-->
  </body>
</html>

app/views/static_pages/timetable.html.erb
<% provide(:title, 'Timetable') %>
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
   <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
   <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
     <title>ChalkSpace | <%= yield(:title) %></title>
  </head>
  <body>
    
      <% if signed_in? %>
      <div class="row demo-samples" style="position:relative;left:-150px;bottom:0;">
        <div class="col-md-4">
           <div class="row demo-navigation" style="position:relative;left:10px;bottom:0;">
            <div class="col-md-6" >
              <div class="btn-toolbar" style="position:relative;left:23px;bottom:0;">
                <div class="btn-group">
                  <%= link_to image_tag("icons/Mortarboard@2x.png", alt: "Rails", width:"30px",height:"22px"),academics_path,class:"btn btn-primary",name:"academics",value:"courses" %>
                  <%= link_to image_tag("icons/Watches@2x.png", alt: "Rails", width:"22px",height:"22px"),timetable_path,class:"btn btn-primary active",name:"academics",value:"timetable" %>
                  <%= link_to image_tag("icons/Calendar@2x.png", alt: "Rails", width:"22px",height:"22px"),"/calendar",class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Clipboard@2x.png", alt: "Rails", width:"22px",height:"22px"),'#',class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Mail@2x.png", alt: "Rails", width:"21px",height:"22px"),root_path,class:"btn btn-primary" %>
                  <%= link_to image_tag("icons/Graph@2x.png", alt: "Rails", width:"22px",height:"22px"),analytics_path,class:"btn btn-primary" %>
                </div>
              </div>
          <div class="demo-col pull-left" style="position:relative;top:-10px;left:5px">
          <ul class="nav nav-list nav-list-vivid">
            <li class="nav-header">Timetable</li>
            <li>
              <a href="#fakelink">
                Exams Schedule
              </a>
            </li>
            <li class="active">
              <a href="#fakelink">
                Homework Submissions
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Daily timetable
              </a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="#fakelink">
                School Events
              </a>
            </li>
            <li>
              <a href="#fakelink">
                Todo List
              </a>
            </li>
          </ul>
        </div> <!-- /nav-list -->
      <h2 align="center">Coming Soon</h2>
      <% else %>
      <div class="center hero-unit">
      <h1>Welcome to the ChalkSpace</h1>

      <h2>
      This is the home page for the
       <a href="http://railstutorial.org/">ChalkSpace</a>
        sample application.<br>
     </h2>
     <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-success" %>
     </div>
     <% end %>
   
  </body>
</html>