login/config/routes.rb
Chalk::Application.routes.draw do
  resources :events

  resources :notices

  resources :tests

  resources :subjects

  resources :teachers

  resources :standards

  get "master/index"

  resources :marks

  resources :students
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/academics',   to: 'static_pages#academics',   via: 'get'
  match '/timetable',    to: 'static_pages#timetable',    via: 'get'
  match '/analytics',   to: 'static_pages#analytics',   via: 'get'
  match '/master/students',   to: 'master#students',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/calendar(/:year(/:month))' => 'static_pages#calendar', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

end

login/app/models/event.rb
class Event < ActiveRecord::Base
attr_accessible :end_at, :name, :start_at
has_event_calendar
end

login/app/models/mark.rb
class Mark < ActiveRecord::Base
end

login/app/models/notice.rb
class Notice < ActiveRecord::Base
end

login/app/models/school.rb
class School < ActiveRecord::Base
end

login/app/models/standard.rb
class Standard < ActiveRecord::Base
end

login/app/models/student.rb
class Student < ActiveRecord::Base
end

login/app/models/subject.rb
class Subject < ActiveRecord::Base
end

login/app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

login/app/models/test.rb
class Test < ActiveRecord::Base
end

login/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

login/app/controllers/standards_controller.rb
class StandardsController < ApplicationController
  before_action :set_standard, only: [:show, :edit, :update, :destroy]

  # GET /standards
  # GET /standards.json
  def index
    @standards = Standard.all
  end

  # GET /standards/1
  # GET /standards/1.json
  def show
  end

  # GET /standards/new
  def new
    @standard = Standard.new
  end

  # GET /standards/1/edit
  def edit
  end

  # POST /standards
  # POST /standards.json
  def create
    @standard = Standard.new(standard_params)

    respond_to do |format|
      if @standard.save
        format.html { redirect_to @standard, notice: 'Standard was successfully created.' }
        format.json { render action: 'show', status: :created, location: @standard }
      else
        format.html { render action: 'new' }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /standards/1
  # PATCH/PUT /standards/1.json
  def update
    respond_to do |format|
      if @standard.update(standard_params)
        format.html { redirect_to @standard, notice: 'Standard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @standard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /standards/1
  # DELETE /standards/1.json
  def destroy
    @standard.destroy
    respond_to do |format|
      format.html { redirect_to standards_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_standard
      @standard = Standard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def standard_params
      params.require(:standard).permit(:standard_school_id, :standard_id, :standard_classteacher_id)
    end
end

login/app/helpers/events_helper.rb
module EventsHelper
end

login/app/helpers/marks_helper.rb
module MarksHelper
end

login/app/helpers/master_helper.rb
module MasterHelper
end

login/app/helpers/notices_helper.rb
module NoticesHelper
end

login/app/helpers/schools_helper.rb
module SchoolsHelper
end

login/app/helpers/sessions_helper.rb
module SessionsHelper
  
   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
   end
      
   def signed_in?
    !current_user.nil?
   end

   def current_user=(user)
    @current_user = user
   end

   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
   end

   def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
   end
 
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

login/app/helpers/standards_helper.rb
module StandardsHelper
end

login/app/helpers/students_helper.rb
module StudentsHelper
end

login/app/helpers/subjects_helper.rb
module SubjectsHelper
end

login/app/helpers/teachers_helper.rb
module TeachersHelper
end

login/app/helpers/tests_helper.rb
module TestsHelper
end

login/app/helpers/users_helper.rb
module UsersHelper
end

login/app/views/standards/_form.html.erb
<%= form_for(@standard) do |f| %>
  <% if @standard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@standard.errors.count, "error") %> prohibited this standard from being saved:</h2>

      <ul>
      <% @standard.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :standard_school_id %><br>
    <%= f.text_field :standard_school_id %>
  </div>
  <div class="field">
    <%= f.label :standard_id %><br>
    <%= f.text_field :standard_id %>
  </div>
  <div class="field">
    <%= f.label :standard_classteacher_id %><br>
    <%= f.text_field :standard_classteacher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

login/app/views/standards/edit.html.erb
<h1>Editing standard</h1>

<%= render 'form' %>

<%= link_to 'Show', @standard %> |
<%= link_to 'Back', standards_path %>

login/app/views/standards/index.html.erb
<h1>Listing standards</h1>

<table>
  <thead>
    <tr>
      <th>Standard school</th>
      <th>Standard</th>
      <th>Standard classteacher</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @standards.each do |standard| %>
      <tr>
        <td><%= standard.standard_school_id %></td>
        <td><%= standard.standard_id %></td>
        <td><%= standard.standard_classteacher_id %></td>
        <td><%= link_to 'Show', standard %></td>
        <td><%= link_to 'Edit', edit_standard_path(standard) %></td>
        <td><%= link_to 'Destroy', standard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Standard', new_standard_path %>

login/app/views/standards/new.html.erb
<h1>New standard</h1>

<%= render 'form' %>

<%= link_to 'Back', standards_path %>

login/app/views/standards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Standard school:</strong>
  <%= @standard.standard_school_id %>
</p>

<p>
  <strong>Standard:</strong>
  <%= @standard.standard_id %>
</p>

<p>
  <strong>Standard classteacher:</strong>
  <%= @standard.standard_classteacher_id %>
</p>

<%= link_to 'Edit', edit_standard_path(@standard) %> |
<%= link_to 'Back', standards_path %>