login/config/routes.rb
Chalk::Application.routes.draw do
  resources :events

  resources :notices

  resources :tests

  resources :subjects

  resources :teachers

  resources :standards

  get "master/index"

  resources :marks

  resources :students
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/academics',   to: 'static_pages#academics',   via: 'get'
  match '/timetable',    to: 'static_pages#timetable',    via: 'get'
  match '/analytics',   to: 'static_pages#analytics',   via: 'get'
  match '/master/students',   to: 'master#students',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/calendar(/:year(/:month))' => 'static_pages#calendar', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

end

login/app/models/event.rb
class Event < ActiveRecord::Base
attr_accessible :end_at, :name, :start_at
has_event_calendar
end

login/app/models/mark.rb
class Mark < ActiveRecord::Base
end

login/app/models/notice.rb
class Notice < ActiveRecord::Base
end

login/app/models/school.rb
class School < ActiveRecord::Base
end

login/app/models/standard.rb
class Standard < ActiveRecord::Base
end

login/app/models/student.rb
class Student < ActiveRecord::Base
end

login/app/models/subject.rb
class Subject < ActiveRecord::Base
end

login/app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

login/app/models/test.rb
class Test < ActiveRecord::Base
end

login/app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

login/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render action: 'show', status: :created, location: @student }
      else
        format.html { render action: 'new' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:student_school_id, :student_standard_id, :student_id, :student_name, :student_address, :student_city, :student_state, :student_phone)
    end
end

login/app/helpers/events_helper.rb
module EventsHelper
end

login/app/helpers/marks_helper.rb
module MarksHelper
end

login/app/helpers/master_helper.rb
module MasterHelper
end

login/app/helpers/notices_helper.rb
module NoticesHelper
end

login/app/helpers/schools_helper.rb
module SchoolsHelper
end

login/app/helpers/sessions_helper.rb
module SessionsHelper
  
   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
   end
      
   def signed_in?
    !current_user.nil?
   end

   def current_user=(user)
    @current_user = user
   end

   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
   end

   def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
   end
 
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

login/app/helpers/standards_helper.rb
module StandardsHelper
end

login/app/helpers/students_helper.rb
module StudentsHelper
end

login/app/helpers/subjects_helper.rb
module SubjectsHelper
end

login/app/helpers/teachers_helper.rb
module TeachersHelper
end

login/app/helpers/tests_helper.rb
module TestsHelper
end

login/app/helpers/users_helper.rb
module UsersHelper
end

login/app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_school_id %><br>
    <%= f.text_field :student_school_id %>
  </div>
  <div class="field">
    <%= f.label :student_standard_id %><br>
    <%= f.text_field :student_standard_id %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.text_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :student_address %><br>
    <%= f.text_area :student_address %>
  </div>
  <div class="field">
    <%= f.label :student_city %><br>
    <%= f.text_field :student_city %>
  </div>
  <div class="field">
    <%= f.label :student_state %><br>
    <%= f.text_field :student_state %>
  </div>
  <div class="field">
    <%= f.label :student_phone %><br>
    <%= f.text_field :student_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

login/app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

login/app/views/students/index.html.erb
<h1>Listing students</h1>

<table>
  <thead>
    <tr>
      <th>Student school</th>
      <th>Student standard</th>
      <th>Student</th>
      <th>Student name</th>
      <th>Student address</th>
      <th>Student city</th>
      <th>Student state</th>
      <th>Student phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.student_school_id %></td>
        <td><%= student.student_standard_id %></td>
        <td><%= student.student_id %></td>
        <td><%= student.student_name %></td>
        <td><%= student.student_address %></td>
        <td><%= student.student_city %></td>
        <td><%= student.student_state %></td>
        <td><%= student.student_phone %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

login/app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

login/app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student school:</strong>
  <%= @student.student_school_id %>
</p>

<p>
  <strong>Student standard:</strong>
  <%= @student.student_standard_id %>
</p>

<p>
  <strong>Student:</strong>
  <%= @student.student_id %>
</p>

<p>
  <strong>Student name:</strong>
  <%= @student.student_name %>
</p>

<p>
  <strong>Student address:</strong>
  <%= @student.student_address %>
</p>

<p>
  <strong>Student city:</strong>
  <%= @student.student_city %>
</p>

<p>
  <strong>Student state:</strong>
  <%= @student.student_state %>
</p>

<p>
  <strong>Student phone:</strong>
  <%= @student.student_phone %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>