config/routes.rb
Chalk::Application.routes.draw do
  resources :tests

  resources :subjects

  resources :teachers

  resources :standards

  get "master/index"
  resources :marks

  resources :students
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/academics',   to: 'static_pages#academics',   via: 'get'
  match '/timetable',    to: 'static_pages#timetable',    via: 'get'
  match '/analytics',   to: 'static_pages#analytics',   via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/calendar(/:year(/:month))' => 'static_pages#calendar', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

end

app/models/event.rb
class Event < ActiveRecord::Base
has_event_calendar
end

app/models/mark.rb
class Mark < ActiveRecord::Base
end

app/models/school.rb
class School < ActiveRecord::Base
end

app/models/standard.rb
class Standard < ActiveRecord::Base
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/subject.rb
class Subject < ActiveRecord::Base
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
end

app/models/teacher_subject_map.rb
class TeacherSubjectMap < ActiveRecord::Base
end

app/models/test.rb
class Test < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @teacher }
      else
        format.html { render action: 'new' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:teacher_school_id, :teacher_id, :teacher_name, :teacher_address, :teacher_city, :teacher_state, :teacher_phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/helpers/master_helper.rb
module MasterHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
   def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
   end
      
   def signed_in?
    !current_user.nil?
   end

   def current_user=(user)
    @current_user = user
   end

   def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
   end

   def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
   end
 
  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end
end

app/helpers/standards_helper.rb
module StandardsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

 def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end

  def event_calendar_options
    { 
      :year => @year,
      :month => @month,
      :event_strips => @event_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"
    }
  end

  def event_calendar
    calendar event_calendar_options do |args|
      event = args[:event]
      %(<a href="/events/#{event.id}" title="#{h(event.name)}">#{h(event.name)}</a>)
    end
  end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :teacher_school_id %><br>
    <%= f.text_field :teacher_school_id %>
  </div>
  <div class="field">
    <%= f.label :teacher_id %><br>
    <%= f.text_field :teacher_id %>
  </div>
  <div class="field">
    <%= f.label :teacher_name %><br>
    <%= f.text_field :teacher_name %>
  </div>
  <div class="field">
    <%= f.label :teacher_address %><br>
    <%= f.text_area :teacher_address %>
  </div>
  <div class="field">
    <%= f.label :teacher_city %><br>
    <%= f.text_field :teacher_city %>
  </div>
  <div class="field">
    <%= f.label :teacher_state %><br>
    <%= f.text_field :teacher_state %>
  </div>
  <div class="field">
    <%= f.label :teacher_phone %><br>
    <%= f.text_field :teacher_phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h1>Listing teachers</h1>

<table>
  <thead>
    <tr>
      <th>Teacher school</th>
      <th>Teacher</th>
      <th>Teacher name</th>
      <th>Teacher address</th>
      <th>Teacher city</th>
      <th>Teacher state</th>
      <th>Teacher phone</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.teacher_school_id %></td>
        <td><%= teacher.teacher_id %></td>
        <td><%= teacher.teacher_name %></td>
        <td><%= teacher.teacher_address %></td>
        <td><%= teacher.teacher_city %></td>
        <td><%= teacher.teacher_state %></td>
        <td><%= teacher.teacher_phone %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Teacher school:</strong>
  <%= @teacher.teacher_school_id %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @teacher.teacher_id %>
</p>

<p>
  <strong>Teacher name:</strong>
  <%= @teacher.teacher_name %>
</p>

<p>
  <strong>Teacher address:</strong>
  <%= @teacher.teacher_address %>
</p>

<p>
  <strong>Teacher city:</strong>
  <%= @teacher.teacher_city %>
</p>

<p>
  <strong>Teacher state:</strong>
  <%= @teacher.teacher_state %>
</p>

<p>
  <strong>Teacher phone:</strong>
  <%= @teacher.teacher_phone %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>